version: '3.8'

services:
  db:
    build:
      context: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  api_server:
    build:
      context: ./api_server
    ports:
      - "666:80"
    depends_on:
      - db
    restart: always

  app_container:
    build:
      context: ./app_container
    volumes:
      - ./app_container/data:/app/data
    depends_on:
      - db
    restart: always

volumes:
  dbdata:
