version: '3.8'

services:
  db:
    build:
      context: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api_server:
    build:
      context: ./api_server
    ports:
      - "666:80"
    depends_on:
      - db
    restart: always

  s3_simulator:
    image: minio/minio
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

  app_container:
    build:
      context: ./main_app
      dockerfile: Dockerfile
    restart: always

volumes:
  dbdata:
  data:
  app:
